### ISSUE TITLE
Problem installing - what version of ruby is required?

### ISSUE THREAD

**Issue by trozware** [Zewo/zewo-dev#8]
Trying to install zewo-dev, I get a chain of errors & warnings as shown.
At one point I did get a folder full of projects but it appeared to be missing a lot, including the crucial HTTPServer.

Here is the version of ruby that I am using so maybe it is not compatible.

```
$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
```

Any ideas on how I should proceed?

```
$ zewodev init
/Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.9/lib/zewo.rb:255: warning: assigned but unused variable - name
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55: warning: loading in progress, circular require considered harmful - /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/ansi.rb
    from /usr/local/bin/zewodev:23:in `<main>'
    from /usr/local/bin/zewodev:23:in `load'
    from /Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.9/bin/zewodev:3:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.9/lib/zewo.rb:10:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj.rb:1:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj.rb:3:in `<module:Xcodeproj>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide.rb:6:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide.rb:13:in `<module:CLAide>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/ansi.rb:111:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/ansi/string_escaper.rb:1:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/argv.rb:218: warning: private attribute?
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/informative_error.rb:17: warning: method redefined; discarding old exit_status
Clone using SSH? -  y/N: n
```

**Comment by Danappelxx** [comment]
It's actually not broken - those are warnings. They will go away after #7 is merged! I'll close this when that happens.

**Comment by trozware** [comment]
I love a speedy response :-)

However it feels 'broken' when it doesn't actually install some or all of the modules.
I will try again after #7 is merged...

**Comment by Danappelxx** [comment]
Fixed! Run `gem update`

**Comment by trozware** [comment]
Thanks Dan, but still no luck. I have been following the instructions on this page: [http://docs.zewo.io/Xcode.html](http://docs.zewo.io/Xcode.html) - are they still valid?

I had uninstalled the zewodev gem, so I re-installed it. I have to use `sudo` to install - does that make a difference to the rest of the process?

When I ran `zewodev init` I got 68 folders installed, but no HTTPServer.
When I ran `zewodev checkout --tag 0.2` or `zewodev checkout --tag 0.3`, I got this error:

```
$ zewodev checkout --tag 0.2
/Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.10/lib/zewo.rb:302:in `block in checkout': undefined local variable or method `repo' for #<Zewo::App:0x007fae3a2406e0> (NameError)
    from /Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.10/lib/zewo.rb:300:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.10/lib/zewo.rb:300:in `checkout'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.10/bin/zewodev:7:in `<top (required)>'
    from /usr/local/bin/zewodev:23:in `load'
    from /usr/local/bin/zewodev:23:in `<main>'
```

**Comment by Danappelxx** [comment]
Looks like there was a mistake in the pr... Use `zewodev setup_osx_dev --version 0.3` instead (it's better, anyway)..

**Comment by trozware** [comment]
FYI but I am giving up for now. Thanks for your help though.

I guess the whole server-side Swift is a bit too new for me at this stage. Interesting to look at but I will wait for a more mature solution to emerge.

```
$ zewodev setup_osx_dev --version 0.3
Cloning repositories...
Cloning paulofaria/stream...
Cloning zewo/ZeroMQ...
Cloning venicex/CLibvenice...
Cloning venicex/IP...
Cloning venicex/UDP...
Cloning venicex/HTTPClient...
Cloning venicex/HTTPSServer...
Cloning venicex/File...
Cloning venicex/ChannelStream...
Cloning swiftx/S4...
Cloning venicex/Venice...
Cloning venicex/TCPSSL...
Cloning venicex/HTTPFile...
Cloning venicex/TCP...
Cloning venicex/HTTPServer...
Cloning venicex/HTTPSClient...
Cloning swiftx/C7...
/Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.10/lib/zewo.rb:302:in `block in checkout': undefined local variable or method `repo' for #<Zewo::App:0x007fbaa3911fa8> (NameError)
    from /Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.10/lib/zewo.rb:300:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.10/lib/zewo.rb:300:in `checkout'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.10/lib/zewo.rb:377:in `setup_osx_dev'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/zewo-dev-0.2.10/bin/zewodev:7:in `<top (required)>'
    from /usr/local/bin/zewodev:23:in `load'
    from /usr/local/bin/zewodev:23:in `<main>'
```

**Comment by Danappelxx** [comment]
Very sorry to hear that - stuff is still rough around the edges (especially in this repository, considering we are primarily Swift programmers with little Ruby experience). Anyway, I finally fixed the issue, for real this time. If you update the gem version to 0.2.12, running `zewodev setup_osx_dev --version 0.3` will succeed and generate all the Xcode projects.

I know it sucks when so much stuff doesn't work, but I really urge you to reconsider giving up on Zewo since `zewo-dev` is really just a convenience tool and does not reflect on the stability nor quality of the Zewo project itself.

**Comment by trozware** [comment]
Dan, I really appreciate your efforts in steering me through this. 
`zewodev setup_osx_dev --version 0.3` did appear to install everything, but there were still missing components when I tried to build, so I abandoned the idea of using Xcode and went back to editing in a text editor and building in Terminal.

Now I am trying to work out how to use Router to detect incoming parameters and create a Response.

Is it always intended that the Zewo server run as a command line program? Are there any plans to integrate it with Apache or to make a buildable into a viewable app?

**Comment by davidask** [comment]
@trozware thanks for your patience. I can tell you, from the first commit this tool was intended to be an ad-hoc solution to Xcode generation for work on Zewo stuff only. It's usefulness was too great for its own good i'm afraid..

**Comment by Danappelxx** [comment]
> but there were still missing components when I tried to build

Man, that is so frustrating...

> Is it always intended that the Zewo server run as a command line program? Are there any plans to integrate it with Apache or to make a buildable into a viewable app?

Well, most of Zewo should run on iOS but we currently don't have plans to run on Apache (I don't really see why you would want that, please enlighten me!), though you can obviously reverse proxy through nginx.

If you'd like to talk more about Zewo I encourage you to join the [zewo slack](http://slack.zewo.io)! We can go more in depth there if you'd like.
